# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d463cf8e569539c9ff5e004634258916b7a2847bdf5c6e50282d44a5283710322b38f3a85107ac772311911b5776962d172e41f1d3db5b77825e0a20c07568a3

test:
  secret_key_base: 80aa0ee7844516c3c0ec465689287f22c5621c67f2a6ebd17c749b99c224ff496cd5de25d0fb75c7f9a79d66e7471c8108a114e1936adc39d34e541673dc24c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
